# Generated by Django 6.0.2 on 2026-02-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sku',
            field=models.CharField(default=3, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
