# Generated by Django 6.0.2 on 2026-02-20 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0009_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='variant',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='inventory',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='online_shop.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='online_shop.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default=6, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_on_hand',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sku',
            field=models.CharField(default=7, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(default=8, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=9, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='barcode',
            field=models.CharField(default=10, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='online_shop.inventorycategory'),
            preserve_default=False,
        ),
    ]
