# Generated by Django 6.0.2 on 2026-02-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0011_category_is_active_category_sort_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
