# Generated by Django 6.0.2 on 2026-02-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0013_loyaltypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryCategory',
        ),
    ]
