# Generated by Django 6.0.2 on 2026-03-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0021_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='points_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
