# Generated by Django 6.0.2 on 2026-03-07 04:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def populate_userprofile_timestamps(apps, schema_editor):
    UserProfile = apps.get_model('registration', 'UserProfile')
    now = timezone.now()
    UserProfile.objects.filter(created_at__isnull=True).update(created_at=now)
    UserProfile.objects.filter(updated_at__isnull=True).update(updated_at=now)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user__username',), 'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        # Add timestamps as nullable first to avoid migration issues on existing rows
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        # Backfill timestamps for existing records
        migrations.RunPython(populate_userprofile_timestamps, reverse_code=noop_reverse),
        # Make timestamps non-nullable after backfill
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Enter a valid phone number.',
                        regex='^\\+?[0-9()\\-\\s]{7,20}$',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
